-- Seed inicial de categorias/subcategorias de despesa e receita.
with raizes as (
    insert into categorias (nome, tipo, parent_id, ordem)
    values
        ('Moradia', 'despesa', null, 1),
        ('Mercado', 'despesa', null, 2),
        ('Restaurantes', 'despesa', null, 3),
        ('Transporte', 'despesa', null, 4),
        ('Saúde', 'despesa', null, 5),
        ('Cuidados pessoais', 'despesa', null, 6),
        ('Compras', 'despesa', null, 7),
        ('Casa', 'despesa', null, 8),
        ('Educação', 'despesa', null, 9),
        ('Lazer', 'despesa', null, 10),
        ('Viagem', 'despesa', null, 11),
        ('Assinaturas', 'despesa', null, 12),
        ('Pets', 'despesa', null, 13),
        ('Tarifas e impostos', 'despesa', null, 14),
        ('Impostos', 'despesa', null, 15),
        ('Trabalho', 'despesa', null, 16),
        ('Investimentos', 'despesa', null, 17),
        ('Outros', 'despesa', null, 18)
    returning id, nome
)
insert into categorias (nome, tipo, parent_id, ordem)
select sub.nome, 'despesa', raizes.id, sub.ordem
from raizes
join (values
    ('Moradia', 'Financiamento Imobiliário', 1),
    ('Moradia', 'Condomínio', 2),
    ('Moradia', 'IPTU', 3),
    ('Moradia', 'Luz', 4),
    ('Moradia', 'Água', 5),
    ('Moradia', 'Gás', 6),
    ('Moradia', 'Internet', 7),
    ('Moradia', 'Manutenção', 8),
    ('Moradia', 'Seguro', 9),
    ('Mercado', 'Supermercado', 1),
    ('Mercado', 'Bebidas', 2),
    ('Restaurantes', 'Restaurante', 1),
    ('Restaurantes', 'Delivery', 2),
    ('Restaurantes', 'Bar', 3),
    ('Transporte', 'Apps de transporte', 1),
    ('Transporte', 'Combustível', 2),
    ('Transporte', 'Transporte público', 3),
    ('Transporte', 'Estacionamento', 4),
    ('Transporte', 'Pedágio', 5),
    ('Transporte', 'Aluguel de carro', 6),
    ('Transporte', 'Multas', 7),
    ('Saúde', 'Plano de saúde', 1),
    ('Saúde', 'Farmácia', 2),
    ('Saúde', 'Consultas', 3),
    ('Saúde', 'Exames', 4),
    ('Saúde', 'Terapia', 5),
    ('Saúde', 'Tratamentos', 6),
    ('Cuidados pessoais', 'Cabelo', 1),
    ('Cuidados pessoais', 'Estética', 2),
    ('Cuidados pessoais', 'Academia', 3),
    ('Compras', 'Roupas/Acessórios', 1),
    ('Compras', 'Cosméticos', 2),
    ('Compras', 'Presentes', 3),
    ('Compras', 'Outros', 4),
    ('Casa', 'Móveis', 1),
    ('Casa', 'Eletrodomésticos', 2),
    ('Casa', 'Decoração', 3),
    ('Casa', 'Utensílios', 4),
    ('Educação', 'Cursos', 1),
    ('Educação', 'Livros', 2),
    ('Educação', 'Material', 3),
    ('Lazer', 'Festas', 1),
    ('Lazer', 'Shows e eventos', 2),
    ('Lazer', 'Jogos', 3),
    ('Lazer', 'Hobbies', 4),
    ('Viagem', 'Passagens', 1),
    ('Viagem', 'Hospedagem', 2),
    ('Viagem', 'Alimentação em viagem', 3),
    ('Viagem', 'Passeios', 4),
    ('Viagem', 'Seguro viagem', 5),
    ('Viagem', 'Compras viagem', 6),
    ('Viagem', 'Conversão para outras moedas', 7),
    ('Assinaturas', 'Celular', 1),
    ('Assinaturas', 'Apps e software', 2),
    ('Assinaturas', 'Nuvem', 3),
    ('Assinaturas', 'Streaming', 4),
    ('Pets', 'Ração', 1),
    ('Pets', 'Veterinário', 2),
    ('Pets', 'Areia', 3),
    ('Pets', 'Farmácia Veterinária', 4),
    ('Pets', 'Outros-Pet', 5),
    ('Tarifas e impostos', 'Anuidade', 1),
    ('Tarifas e impostos', 'Tarifa bancária', 2),
    ('Tarifas e impostos', 'Juros', 3),
    ('Tarifas e impostos', 'IOF', 4),
    ('Tarifas e impostos', 'Multa de atraso', 5),
    ('Tarifas e impostos', 'Imposto de Renda', 6),
    ('Impostos', 'Imposto de renda', 1),
    ('Impostos', 'INSS', 2),
    ('Impostos', 'Outros impostos', 3),
    ('Trabalho', 'OAB', 1),
    ('Investimentos', 'Aporte', 1),
    ('Investimentos', 'Previdência', 2),
    ('Investimentos', 'Reserva de emergência', 3),
    ('Outros', 'A confirmar', 1),
    ('Outros', 'Saque', 2),
    ('Outros', 'Diversos', 3)
) as sub(raiz_nome, nome, ordem) on sub.raiz_nome = raizes.nome;

insert into categorias (nome, tipo, parent_id, ordem)
values
    ('Salário', 'receita', null, 1),
    ('Aluguel Posto - RCP', 'receita', null, 2),
    ('Outros Rendimentos', 'receita', null, 3);
